##[pylyzer] failed /home/jepi/Documents/NSDSYST-MCO2/.venv/lib/python3.12/site-packages/urllib3/util/connection.py 1752607604 4444
.___v_desugar_1: Never
.annotations: Never
.socket: Never

.typing: Never

.___v_desugar_2: Never
.LocationParseError: Never
.___v_desugar_3 = pyimport "timeout"
.timeout = pyimport "timeout"
._DEFAULT_TIMEOUT: Never
._TYPE_TIMEOUT: Never
._TYPE_SOCKET_OPTIONS: Never

.___v_desugar_4: Never
.BaseHTTPConnection: Never


.is_connection_dropped: (conn: Obj) -> Bool
.create_connection: (address: global::Tuple([Str, Int]), timeout: Obj := Obj, source_address: NoneType or global::Tuple([Str, Int]) := NoneType or global::Tuple([Str, Int]), socket_options: Obj := Obj) -> Never
._set_socket_options: (sock: Obj, options: Obj) -> NoneType
.allowed_gai_family: () -> Never
._has_ipv6: (host: Str) -> Bool
.HAS_IPV6: Bool
